# Generated by Django 4.0.8 on 2023-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsgvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsgvo_kz', models.CharField(max_length=2)),
                ('dsgvo_beschreibung', models.CharField(max_length=100)),
                ('emarsys_upload', models.BooleanField(default=False)),
                ('matching_mandantenuebergreifend', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'dsgvo',
                'db_table': 'sdDsgvo',
            },
        ),
        migrations.CreateModel(
            name='Herkunft',
            fields=[
                ('herkunft_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='HerkunftID')),
                ('slug', models.SlugField(unique=True, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Herkunft')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Aktiv?')),
            ],
            options={
                'verbose_name_plural': 'Herkunft',
                'db_table': 'sdHerkunft',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Kommunikationsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=20)),
                ('beschreibung', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Kommunikationsarten',
                'db_table': 'sdKommunikationsart',
            },
        ),
        migrations.CreateModel(
            name='Mandant',
            fields=[
                ('mandant_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MandantID')),
                ('nr', models.PositiveIntegerField(unique=True, verbose_name='Mandant-Nr')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Mandant')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Aktiv?')),
            ],
            options={
                'verbose_name_plural': 'Mandanten',
                'db_table': 'sdMandant',
                'ordering': ['nr'],
            },
        ),
    ]
