# Generated by Django 4.0.8 on 2023-03-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsgvo',
            old_name='emarsys_upload',
            new_name='newsletter_upload',
        ),
    ]
